/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._common._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.net.URL;

public class _bridge__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=KSC5601");
    request.setCharacterEncoding("KSC5601");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
       //---------------------- GENICS ASSOCIATES ------------------------// 
      out.write(_jsp_string1, 0, _jsp_string1.length);
      
request.setCharacterEncoding("euc-kr");
response.setHeader("Cache-Control","no-store");   
response.setHeader("Pragma","no-cache");   
response.setDateHeader("Expires",0);   
if (request.getProtocol().equals("HTTP/1.1")) { 
	response.setHeader("Cache-Control", "no-cache"); 
}

String sso_domain = "http://sso2.chosun.com";
String fam_domain = "http://"+request.getServerName();
String server_url = "http://"+request.getServerName();
String file_ext = "jsp";
String token_session = (String)session.getAttribute("ENC_TOKEN"); // \uc778\uc99d\uc11c\ubc84\uc5d0\uc11c \uc14b\ud305\ud55c \uc778\uc99d\ud1a0\ud070\uac12
String sso_session = (String)session.getAttribute("SSO_INFO");  // \uc778\uc99d\uc11c\ubc84\uc5d0\uc11c \uc5f0\uacc4\uc11c\ubc84\ub85c \ub118\uaca8\uc8fc\ub294 \uc0ac\uc6a9\uc790 \uc815\ubcf4
String sp_session = (String)session.getAttribute("SP_SESSION"); // \ud574\ub2f9\uc2dc\uc2a4\ud15c \uc5c5\ubb34\uc138\uc158(\uba54\ub274\ub098 \uad8c\ud55c\ub4f1):SP=Service Provider
String sso_id = null;
String req_url = request.getRequestURL().toString();
//String message = " IP \ucef4\ud4e8\ud130\uc5d0\uc11c \ub85c\uadf8\uc778\uc744 \ud558\uc600\uc2b5\ub2c8\ub2e4. \uc2dc\uc2a4\ud15c\uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.";

if(sso_session != null && !"".equals(sso_session) && !"null".equals(sso_session)) {
	String[] ssoInfos	= sso_session.split("\\$\\$");
	sso_id = ssoInfos[1];
}

      out.write('\n');
       
	if(sso_id==null){
	//	response.sendRedirect("/");
	}

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((fam_domain));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((fam_domain ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((fam_domain ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((sso_id));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((sso_domain));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((sso_domain));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((sso_domain));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((sso_domain));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((fam_domain));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((file_ext));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((fam_domain));
      out.write(_jsp_string13, 0, _jsp_string13.length);
       //---------------------- GENICS ASSOCIATES ------------------------// 
      out.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/jsp/bridge.jsp"), -3674354877187386199L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("genics/sso_inc/inc_agent.jsp"), 6813920044047700591L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("genics/sso_inc/inc_session.jsp"), 2173784544387787443L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string12;
  private final static char []_jsp_string14;
  private final static char []_jsp_string5;
  private final static char []_jsp_string13;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string9;
  private final static char []_jsp_string0;
  private final static char []_jsp_string10;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string11;
  private final static char []_jsp_string7;
  static {
    _jsp_string12 = "\"></iframe>\n\n<meta http-equiv=\"refresh\" content=\"60;url=".toCharArray();
    _jsp_string14 = " \n<html>\n<head>\n<script language=\"javascript\">\n	function jsMainOpen(){\n		var winID = \"winTFFramework\";	// TF Framework Popup Window ID\n		var newWin = null				// TF Framework Popup Window Object\n		\n		var TargetUrl = \"/common/jsp/main.jsp\";  \n		\n		window.location.href = TargetUrl;\n		/*\n		newWin = window.open(TargetUrl, winID, \"left=0,top=0,width=1220,height=880,menubar=no,toolbar=no,scrollbars=auto,status=no,location=no,resizable=yes\");\n		newWin.focus();\n		\n		if (newWin == null) {\n			alert(\"\ud31d\uc5c5\uc774 \ucc28\ub2e8\ub418\uc5b4\uc788\uc2b5\ub2c8\ub2e4.\\n\\n\ud31d\uc5c5 \ucc28\ub2e8\uc744 \ud574\uc81c\ud574 \uc8fc\uc2dc\uae30 \ubc14\ub78d\ub2c8\ub2e4.\");\n			return;\n		}\n		\n		top.opener = parent;\n		parent.close();\n		*/\n	}\n</script>\n</head>\n<body onload=\"jsMainOpen()\">\n<form name=\"form1\" method=\"post\">\n</form>\n</body>\n</html>".toCharArray();
    _jsp_string5 = "/genics/sso_inc/webtoolkit.base64.js\"></script>\n<script type=\"text/JavaScript\">\nvar sso_id = '".toCharArray();
    _jsp_string13 = "/genics/sso_inc/inc_agent.jsp\">\n\n\n".toCharArray();
    _jsp_string2 = "\n<form name=\"connect_actor\" method=\"post\" style=\"display:inline;\">\n	<input type='hidden' name='a' value='SsoActionApp'>\n	<input type='hidden' name='c' value = ''>\n	<input type='hidden' name='sso_token' value=''>\n	<input type='hidden' name='target_url' value='".toCharArray();
    _jsp_string6 = "';\nfunction BSSO_sso_process(str, fs, ip, msg) {\n	var sso_token = str; // \uc778\uc99d\uc11c\ubc84\uc5d0\uc11c \uc778\uc99d\ud6c4 \ub118\uaca8\uc8fc\ub294 \uc778\uc99d\ud1a0\ud070\n	if(sso_id == null || sso_id == '' || sso_id == 'null') { // \ud574\ub2f9 SP\uc5d0 \uc138\uc158\uc774 \uc5c6\ub2e4\uba74\n		if(sso_token != null && sso_token != '' && sso_token != 'null') { // \ud558\uc9c0\ub9cc \uc778\uc99d\uc11c\ubc84\uc5d0\uc11c \uc138\uc158\uc774 \uc788\ub2e4\uba74\n			// \ub85c\uadf8\uc778 \ucc98\ub9ac\ud55c\ub2e4.\n			BSSO_login_process(str);\n		}\n	}else{	// \uc774\ubbf8 \uc138\uc158\uc774 \ub9fa\uc5b4\uc838 \uc788\ub2e4\uba74\n		if(sso_token == null || sso_token == '' || sso_token == 'null') { // \ud558\uc9c0\ub9cc \uc778\uc99d\uc11c\ubc84\uc5d0\uc11c \uc138\uc158\uc774 \uc5c6\ub2e4\uba74\n			// \ub85c\uadf8\uc544\uc6c3 \ucc98\ub9ac\ud55c\ub2e4.\n			BSSO_logout_process();\n		}else{\n			if(fs == '1') { // \uc911\ubcf5\uc811\uc18d \uc0c1\ud0dc\uc5d0\uc11c  \uba54\uc2dc\uc9c0 \uba85\ub839 \uc138\uc158\uc744 \uc0ad\uc81c\ud558\uae30 \uc704\ud55c \uad6c\ubb38\n				alert(ip + ' '+Base64.decode(msg));\n				//BSSO_login_process(str);\n				//\ub2e4\ub978 \ucef4\ud4e8\ud130\uc5d0\uc11c \uc811\uc18d\ud588\ub294 \uc9c0 \uc5ec\ubd80\ub97c \uc54c\ub9ac\ub294 \uc138\uc158\uc744 \uc0ad\uc81c\ud55c\ub2e4.\n				document.getElementById('_sso_frame').src = \"".toCharArray();
    _jsp_string9 = "/cert.genics';\n	f.c.value = '1002';\n	f.action_type.value = 'LO';\n	f.target = '_top'\n	f.sso_id.value = sso_id;\n	f.submit();\n}\n</script>\n\n<iframe id=\"_sso_frame\" name=\"_sso_frame\" width=\"500\" height=\"0\" frameborder=\"0\" style=\"display:inline;\" src=\"".toCharArray();
    _jsp_string0 = "\n\n\n".toCharArray();
    _jsp_string10 = "/sso_auth.jsp?fam_domain=".toCharArray();
    _jsp_string4 = "/genics/client_action.jsp'>\n	<input type='hidden' name='action_type' value=''>\n	<input type='hidden' name='sso_id' value=''>\n</form>\n\n<script type=\"text/JavaScript\" src=\"".toCharArray();
    _jsp_string8 = "/cert.genics';\n	f.c.value = '1003';\n	f.action_type.value = 'XX';\n	f.target = '_top'\n	f.sso_token.value = str;\n	f.submit();\n}\n\nfunction BSSO_logout_process() {\n	var f = document.connect_actor;\n	f.action = '".toCharArray();
    _jsp_string1 = " \n\n".toCharArray();
    _jsp_string3 = "'>\n	<input type='hidden' name='action_url' value='".toCharArray();
    _jsp_string11 = "&file_ext=".toCharArray();
    _jsp_string7 = "/function/initMsgProc.jsp\";\n			}else if(fs == '2') { // \uc138\uc158\uc744 \uac15\uc81c\ub85c \uc885\ub8cc\ud558\ub294 \uacbd\uc6b0\n				alert(ip + ' '+Base64.decode(msg));\n				BSSO_logout_process();\n			}else if(fs == '5') { // \uad00\ub9ac\uc790\uac00 \uc138\uc158\uc744 \uac15\uc81c\ub85c \ub04a\ub294 \uacbd\uc6b0\n				alert(Base64.decode(msg));\n				BSSO_logout_process();\n			}\n		}\n	}\n}\n\nfunction BSSO_login_process(str) {\n	var f = document.connect_actor;\n	f.action = '".toCharArray();
  }
}
