/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._common._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _install__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=EUC-KR");
    request.setCharacterEncoding("EUC-KR");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
	String domainName = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath();
	
	String userid = request.getParameter("user_id");
	String userpasswd = request.getParameter("user_passwd");
	
	String configURL  = domainName +"/install/config.xml";
	String configDir  = "/install";
	
	String serverPath = domainName +"/install";

	String intendPath = "";
	

      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((serverPath));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((configURL));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((userid));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((userpasswd));
      out.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/jsp/install.jsp"), -2088534147100380417L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  static {
    _jsp_string5 = "\" name=\"user_passwd\">\r\n</form>\r\n\r\n<OBJECT id=\"smartUpdater\" classid=\"CLSID:ED5D862B-6A06-46de-A929-F2C588742CBD\" width=\"0\" height=\"0\" CODEBASE=\"/install/TFSmartUpdater_m.cab#version=2,6,3,5\">\r\n	<PARAM name=\"deleteZipFile\" value=\"true\"/>\r\n	<PARAM name=\"registry\" value=\"false\"/>\r\n	<PARAM name=\"configDir\" value=\"c:\\install\"/>\r\n	<PARAM name=\"enableLog\" value =\"true\"/>\r\n	<PARAM name=\"selfUi\" value=\"true\"/>\r\n	<PARAM name=\"dlgNotClose\" value=\"true\"/>\r\n	<PARAM name=\"hideDownloadCancel\" value=\"true\"/>\r\n	<PARAM name=\"stopNotFindContent\" value=\"false\"/>\r\n	<PARAM name=\"useNameTarget\" value=\"true\"/>\r\n</OBJECT>\r\n</BODY>\r\n</HTML>".toCharArray();
    _jsp_string1 = "\r\n<HTML>\r\n<HEAD>\r\n<TITLE>\uc870\uc120\uc77c\ubcf4\ud1b5\ud569\uc815\ubcf4\uc9c0\uc6d0\uc2dc\uc2a4\ud15c [TFSmartUpdater]</TITLE>\r\n<SCRIPT language=\"JavaScript\">\r\nfunction window::onLoad(){\r\n	//\ud658\uacbd \ubcc0\uc218 \uc124\uc815\r\n	\r\n	smartUpdater.setCustomDir(\"{server}\", \"".toCharArray();
    _jsp_string3 = "\")==true)\r\n	{\r\n		var obj = document.myform;\r\n		obj.action = \"/common/jsp/bridge.jsp\";\r\n		obj.submit();\r\n	}\r\n	else {\r\n		alert(\"TFSmartUpdater\uac00 \uc124\uce58 \uc911 \uc5d0\ub7ec\uac00 \ubc1c\uc0dd\ud588\uc2b5\ub2c8\ub2e4. \uad00\ub9ac\uc790\uc5d0\uac8c \ubb38\uc758\ud558\uc2ed\uc2dc\uc624.\");\r\n	}\r\n}\r\n</SCRIPT>\r\n</HEAD>\r\n<BODY>\r\n\r\n<form name=\"myform\" method=\"POST\">\r\n<input type=\"hidden\" value=\"".toCharArray();
    _jsp_string2 = "\" );\r\n	smartUpdater.setCustomDir(\"{intend}\", \"c:/install\" );\r\n	//smartUpdater.setStyle2(\"resizable=no, location=no, menubar=no, toolbar=no, status=yes, fullscreen=no\");\r\n	//smartUpdater.setIEResizable(false);\r\n	\r\n	\r\n	\r\n	if (smartUpdater.getConfig(\"".toCharArray();
    _jsp_string4 = "\" name=\"user_id\">\r\n<input type=\"hidden\" value=\"".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
  }
}
