/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._common._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import kr.co.comsquare.rwXmlLib.*;
import kr.co.comsquare.db.*;
import kr.co.comsquare.util.Tokenizer;
import chosun.ciis.co.mng.rec.*;
import chosun.ciis.co.mng.ds.*;;

public class _leftmenu__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/xml; charset=EUC-KR");
    request.setCharacterEncoding("EUC-KR");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // http 1.1
  response.setHeader("Pragma","No-cache"); // http 1.0
	response.setDateHeader("Expires", 0); 	

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	RwXml rx = new RwXml();
	CO_MNG_1010_LDataSet ds = (CO_MNG_1010_LDataSet)request.getAttribute("ds");
	String closeYn = "";
	String subCloseYn = "";
	String endCloseYn = "";

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((ds.menuId));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((ds.menuId));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
	for(int i = 0; i < ds.curlist.size(); i++) {
		CO_MNG_1010_LCURLISTRecord rec = (CO_MNG_1010_LCURLISTRecord)ds.curlist.get(i);
		if ( "1".equals(rec.menu_levl) ){
			if ( "N".equals(endCloseYn) ){
				endCloseYn = "Y";

      out.write(_jsp_string5, 0, _jsp_string5.length);
      				
			}
			if ( "N".equals(subCloseYn) ){
				subCloseYn = "Y";

      out.write(_jsp_string6, 0, _jsp_string6.length);
      			
			}						
			if ( "N".equals(closeYn) ){

      out.write(_jsp_string7, 0, _jsp_string7.length);
      			
			}

			closeYn = "N";

      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((rec.menu_id));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rec.menu_nm));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rec.exctl_catl));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rec.exec_url));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      		
		} else if ( "2".equals(rec.menu_levl) ){
			if ( "N".equals(endCloseYn) ){
				endCloseYn = "Y";

      out.write(_jsp_string5, 0, _jsp_string5.length);
      				
			}		
			if ( "N".equals(subCloseYn) ){

      out.write(_jsp_string6, 0, _jsp_string6.length);
      			
			}
			subCloseYn = "N";

      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((rec.menu_id));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rec.menu_nm));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rec.exctl_catl));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rec.exec_url));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
		} else if ( "3".equals(rec.menu_levl) ){
			if ( "N".equals(endCloseYn) ){
				endCloseYn = "Y";

      out.write(_jsp_string12, 0, _jsp_string12.length);
      				
			}		
			endCloseYn = "N";

      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((rec.menu_id));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rec.menu_nm));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rec.exctl_catl));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rec.exec_url));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      
		} else if ( "4".equals(rec.menu_levl) ){

      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((rec.menu_id));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rec.menu_nm));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((rec.exctl_catl));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((rec.exec_url));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      	
		}
	} 
	if ( "N".equals(endCloseYn) ){

      out.write(_jsp_string16, 0, _jsp_string16.length);
      	
	}
	if ( "N".equals(subCloseYn) ){

      out.write(_jsp_string6, 0, _jsp_string6.length);
      	
	}
	if ( "N".equals(closeYn) ){

      out.write(_jsp_string7, 0, _jsp_string7.length);
      	
	}

      out.write(_jsp_string17, 0, _jsp_string17.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/jsp/leftmenu.jsp"), -6814158790547532481L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string11;
  private final static char []_jsp_string12;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string5;
  private final static char []_jsp_string16;
  private final static char []_jsp_string17;
  private final static char []_jsp_string6;
  private final static char []_jsp_string15;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string14;
  private final static char []_jsp_string3;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string13;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  static {
    _jsp_string11 = "\r\n				<detail itemID=\"".toCharArray();
    _jsp_string12 = "	\r\n					</Subdetail>\r\n".toCharArray();
    _jsp_string2 = "\r\n	<Main itemID=\"".toCharArray();
    _jsp_string1 = "\r\n<?xml version=\"1.0\" encoding=\"EUC-KR\"?>\r\n\r\n".toCharArray();
    _jsp_string5 = "				\r\n					</Subdetail>\r\n".toCharArray();
    _jsp_string16 = "\r\n					</Subdetail>\r\n".toCharArray();
    _jsp_string17 = "\r\n	</Main>\r\n\r\n	".toCharArray();
    _jsp_string6 = "\r\n				</detail>\r\n".toCharArray();
    _jsp_string15 = "\"/>\r\n".toCharArray();
    _jsp_string4 = "\">\r\n".toCharArray();
    _jsp_string9 = "\" crud=\"".toCharArray();
    _jsp_string14 = "\r\n						<enddetail itemID=\"".toCharArray();
    _jsp_string3 = "\" name=\"".toCharArray();
    _jsp_string8 = "				\r\n			<Sub itemID=\"".toCharArray();
    _jsp_string7 = "\r\n			</Sub>\r\n".toCharArray();
    _jsp_string13 = "\r\n					<Subdetail itemID=\"".toCharArray();
    _jsp_string10 = "\" url=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
