/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._common._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.text.*;
import java.lang.*;
import java.util.*;
import java.io.*;
import somo.framework.util.*;

public class _main__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;

  
      // \uc804\ub2ec\ub41c \ucfe0\ud0a4\uc5d0 \uc124\uc815\ub41c \uac12\uc744 \uc5bb\uc5b4\uc11c \ub9ac\ud134\ud55c\ub2e4.
      public String GetCookie(HttpServletRequest req, HttpServletResponse res, String param) throws Exception{
          String ret = "";
          Cookie[] cookies = req.getCookies();
          if(cookies != null){
              for(int i=0; i<cookies.length; i++){
                  if(cookies[i].getName().equals(param)){
                      ret = cookies[i].getValue();
  					break;
                  }
              }
          }
          return ret;
      }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=KSC5601");
    request.setCharacterEncoding("KSC5601");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
		// LDAP \uc0ac\uc6a9\uc790 \uc815\ubcf4 Request \ucc98\ub9ac (\ud604 CRM \uc0ac\uc6a9\uc911\uc778 \ud56d\ubaa9\ub4e4)
		String uid			= request.getHeader("UID")   		== null ? "" : Util.Uni2Ksc(request.getHeader("UID")); 		 	  // \uc544\uc774\ub514
		String emp_no       = request.getHeader("EMP_NO")       == null ? "" : Util.Uni2Ksc(request.getHeader("EMP_NO"));         // \uc0ac\ubc88
		String emp_nm       = request.getHeader("EMP_NM")       == null ? "" : Util.Uni2Ksc(request.getHeader("EMP_NM"));         // \uc131\uba85
		String cmpycd       = request.getHeader("CMPYCD")       == null ? "" : Util.Uni2Ksc(request.getHeader("CMPYCD"));         // \ud68c\uc0ac
		String cmpynm       = request.getHeader("CMPYNM")       == null ? "" : Util.Uni2Ksc(request.getHeader("CMPYNM"));         // \ud68c\uc0ac		
		String deptcd       = request.getHeader("DEPTCD")       == null ? "" : Util.Uni2Ksc(request.getHeader("DEPTCD"));         // \ubd80\uc11c
		String deptnm       = request.getHeader("DEPTNM")       == null ? "" : Util.Uni2Ksc(request.getHeader("DEPTNM"));         // \ubd80\uc11c\uba85
		String selldeptcd	= request.getHeader("SELLDEPTCD")   == null ? "" : Util.Uni2Ksc(request.getHeader("SELLDEPTCD"));     // \ud310\ub9e4\ubd80\uc11c
		String selldeptnm   = request.getHeader("SELLDEPTNM")   == null ? "" : Util.Uni2Ksc(request.getHeader("SELLDEPTNM"));     // \ud310\ub9e4\ubd80\uc11c\uba85
		String areacd       = request.getHeader("AREACD")       == null ? "" : Util.Uni2Ksc(request.getHeader("AREACD"));         // \uad00\ub9ac\uc9c0\uc5ed\ucf54\ub4dc
		String areanm       = request.getHeader("AREANM")       == null ? "" : Util.Uni2Ksc(request.getHeader("AREANM"));         // \uad00\ub9ac\uc9c0\uc5ed\uba85
		String deptplacyn   = request.getHeader("DEPTPLACYN")   == null ? "" : Util.Uni2Ksc(request.getHeader("DEPTPLACYN"));     // \ubd80\uc11c\uc7a5\uc5ec\ubd80
		String jobcd        = request.getHeader("JOBCD")        == null ? "" : Util.Uni2Ksc(request.getHeader("JOBCD"));          // \uc5c5\ubb34\uad6c\ubd84
		String jobnm        = request.getHeader("JOBNM")        == null ? "" : Util.Uni2Ksc(request.getHeader("JOBNM"));          // \uc5c5\ubb34\uad6c\ubd84\uba85
		String posicd       = request.getHeader("POSICD")       == null ? "" : Util.Uni2Ksc(request.getHeader("POSICD"));         // \uc9c1\ucc45\ucf54\ub4dc
		String posinm       = request.getHeader("POSINM")       == null ? "" : Util.Uni2Ksc(request.getHeader("POSINM"));         // \uc9c1\ucc45\uba85
		String usertypecd   = request.getHeader("USERTYPECD")   == null ? "" : Util.Uni2Ksc(request.getHeader("USERTYPECD"));     // \uc0ac\uc6d0\uad6c\ubd84\ucf54\ub4dc
		String usertypenm   = request.getHeader("USERTYPENM")   == null ? "" : Util.Uni2Ksc(request.getHeader("USERTYPENM"));     // \uc0ac\uc6d0\uad6c\ubd84\uba85
		String email        = request.getHeader("EMAIL")        == null ? "" : Util.Uni2Ksc(request.getHeader("EMAIL"));          // \uc774\uba54\uc77c
		String dealdeptcd   = request.getHeader("DEALDEPTCD")   == null ? "" : Util.Uni2Ksc(request.getHeader("DEALDEPTCD"));     // \uad00\ub9ac\ubd80\uc11c\ucf54\ub4dc
		String dealdeptnm   = request.getHeader("DEALDEPTNM")   == null ? "" : Util.Uni2Ksc(request.getHeader("DEALDEPTNM"));	  // \uad00\ub9ac\ubd80\uc11c\uba85

		// CIIS \ucd94\uac00 \ud56d\ubaa9\ub4e4
		String hdqtcd		= request.getHeader("HDQTCD")   	== null ? "" : Util.Uni2Ksc(request.getHeader("HDQTCD")); 			// \ubcf8\ubd80
		String hdqtnm		= request.getHeader("HDQTNM")   	== null ? "" : Util.Uni2Ksc(request.getHeader("HDQTNM")); 			// \ubcf8\ubd80\uba85
		String partcd		= request.getHeader("PARTCD")   	== null ? "" : Util.Uni2Ksc(request.getHeader("PARTCD")); 			// \ud30c\ud2b8\ucf54\ub4dc
		String partnm		= request.getHeader("PARTNM")   	== null ? "" : Util.Uni2Ksc(request.getHeader("PARTNM")); 			// \ud30c\ud2b8\uba85
		String hdqtplacyn	= request.getHeader("HDQTPLACYN") 	== null ? "" : Util.Uni2Ksc(request.getHeader("HDQTPLACYN")); 		// \ubcf8\ubd80\uc7a5\uc5ec\ubd80
		String partplacyn	= request.getHeader("PARTPLACYN") 	== null ? "" : Util.Uni2Ksc(request.getHeader("PARTPLACYN")); 		// \ud30c\ud2b8\uc7a5\uc5ec\ubd80
		String dealmedicd	= request.getHeader("DEALMEDICD")  	== null ? "" : Util.Uni2Ksc(request.getHeader("DEALMEDICD")); 		// \uad00\ub9ac\ub9e4\uccb4\ucf54\ub4dc
		String mobile	= request.getHeader("MOBILE")  	== null ? "" : Util.Uni2Ksc(request.getHeader("MOBILE")); 		// \uad00\ub9ac\ub9e4\uccb4\ucf54\ub4dc
		

//	uid="c191003";	
//	emp_no="191003";
//	deptcd="154500";
//	deptnm="CSI\ud300";
//	cmpycd="100";
//	emp_nm="\uc774\uae30\ucd98";
//	dealmedicd = "1";

//	uid="c190053";	
//	emp_no="190053";
//	deptcd="154500";
//	deptnm="CSI\ud300";
//	cmpycd="100";
//	emp_nm="\uc774\uae30\uc6c5";
	
//	uid="c153001";	
//	emp_no="153001";
//	deptcd="154500";
//	deptnm="CSI\ud300";
//	cmpycd="100";
//	emp_nm="\ubc29\uc6b0\uc601";

// uid="c193057";//"c153001";
// emp_no="193057";//"210001";
// deptcd="541100";//"361100";
//  deptnm="AD\ud50c\ub798\ub2dd\ud300";//"\uc784\uc6d0\uc2e4";
//  cmpycd="100";
//  cmpynm="\uc870\uc120\uc77c\ubcf4";
//  emp_nm="\ubc15\ub0a8\uaddc";
  
//  uid="c153001";
//  uid="dit0010";  
//  emp_no="210001";
//  emp_no="it0010";  
//  deptcd="361100";
 // deptnm="\uc784\uc6d0\uc2e4";
//  cmpycd="100";
 // cmpynm="\uc870\uc120\uc77c\ubcf4";
 // emp_nm="\ubc29\uc6b0\uc601";
  
  //uid="c194062";
  //emp_no="194062";
  //deptcd="361100";
  //deptnm="AD\ubcf8\ubd80";
  //cmpycd="100";
  //cmpynm="\uc870\uc120\uc77c\ubcf4";
  //emp_nm="\ub3d9\ud76c\uc6b1";  
  
//  uid="a211127";
//  emp_no="211127";
//  deptcd="361100";
//  deptnm="cstv";
//  cmpycd="500";
//  cmpynm="cstv";
 // emp_nm="\uc870\uc120\ubc29\uc1a1";
  
//  uid="a211510";
//  emp_no="211510";
//  deptcd="255000";
//  deptnm="cstv";
//  cmpycd="500";
//  cmpynm="cstv";
//  emp_nm="\uc870\uc120\ubc29\uc1a1";  

//TV\uc870\uc120 \uc778\uc0ac
	uid="a211095";	
	emp_no="211095";
	deptcd="700200";
	deptnm="\uc778\uc0ac\ud300";
	cmpycd="500";
	emp_nm="\uae40\ub355\uc601";	


//TV\uc870\uc120 \uc778\uc0ac
    uid="cit0022";	
	emp_no="it0022";
	deptcd="000000";
	deptnm="\uc778\uc0ac\ud300";
	cmpycd="100";
	  emp_nm="test";	

   //\uad11\uace0\uc9c0\uc0ac
	uid="c00038160";	
	emp_no="00038160";
	deptcd="000000";
	deptnm="\uac15\ub0a8\uad11\uace0";
	cmpycd="100";
	emp_nm="\uae40\uc0c1\ud6c8";	

	//\uc778\uc0ac
	uid="cit0022";	
	emp_no="it0022";
	deptcd="000000";
	deptnm="MIS\ud300";
	cmpycd="100";
	emp_nm="\uc774\uac00\uc5f0";			
	
//\uc778\uc0ac\ud3c9\uac00
       uid="c189034";      emp_no="189034";
    deptcd="250000";   cmpynm="\uc870\uc120\uc77c\ubcf4"; deptnm="\ud3b8\uc9d1\uad6d";
   cmpycd="100";   emp_nm="\uc774\ucda9\uc77c"; 


//TV\uc870\uc120 \uad11\uace0
	uid="ait0015";	
	emp_no="ait0015";
	deptcd="154500";
	deptnm="MIS\ud300";
	cmpycd="500";
	emp_nm="\uae40\uc0c1\ud6c8";	
 
   	//\ub274\ubbf8\ub514\uc5b4
	uid="c212006";	
	emp_no="212006";
	deptcd="570000";
	deptnm="\ub274\ubbf8\ub514\uc5b4\uc2e4";
	cmpycd="100";
	emp_nm="\uc720\uc120\uc544";	
	dealmedicd	 = "5"; 

//\ucd9c\ud310 \ub274\uc2a4\ud504\ub808\uc2a4 
 uid="x213057";
 emp_no="213057";
 deptcd="010500";
 deptnm="\uc870\uc120\uba54\uac70\uc9c4";
 cmpycd="326";
 cmpynm="\uc870\uc120\uba54\uac70\uc9c4";
 emp_nm="\uc870\uc120\uba54\uac70\uc9c4";	
 dealmedicd	 = "2";	 
 
 	  //\uad11\uace0
	uid="cit0015";	
	emp_no="it0015";
	deptcd="360000";
	deptnm="MIS\ud300";
	cmpycd="100";
	emp_nm="\uae40\uc0c1\ud6c8";				
	
  dealmedicd	 = "3";              
		// LDAP \uc0ac\uc6a9\uc790 \uc815\ubcf4 Session \ucc98\ub9ac
		
		session.setAttribute("uid"			,uid		); 		// \uc544\uc774\ub514
		//	\uc790\uc7ac\uc5d0\uc11c \ucd94\uac00\ud558\ub294 \ub85c\uc9c1
		//	\ubd84\uacf5\uc7a5\ubc0f \uc790\ud68c\uc0ac\uc5d0\uc11c \ub85c\uadf8\uc778\ud558\ub294 \uacbd\uc6b0 \uc0ac\ubc88\uc774 \uc5c6\uc774 \uc544\uc774\ub514\ub9cc \uc788\uac8c \ub41c\ub2e4.
		//	\uc544\uc774\ub514\ub97c \uac00\uc9c0\uace0 \uc0ac\ubc88\uc73c\ub85c \uc0ac\uc6a9
		System.out.println("emp_no=_" + emp_no + "_");
		if (emp_no.equals("")){
			session.setAttribute("emp_no"		,uid     );      // \uc0ac\ubc88
		} else {
			session.setAttribute("emp_no"		,emp_no     );      // \uc0ac\ubc88
		}
		session.setAttribute("emp_nm"		,emp_nm    	);      // \uc131\uba85
		session.setAttribute("cmpycd"		,cmpycd     );      // \ud68c\uc0ac
		session.setAttribute("cmpynm"		,cmpynm     );      // \ud68c\uc0ac
		session.setAttribute("deptcd"		,deptcd     );      // \ubd80\uc11c
		session.setAttribute("deptnm"		,deptnm     );      // \ubd80\uc11c\uba85
		session.setAttribute("selldeptcd"   ,selldeptcd );      // \ud310\ub9e4\ubd80\uc11c
		session.setAttribute("selldeptnm"   ,selldeptnm );      // \ud310\ub9e4\ubd80\uc11c\uba85
		session.setAttribute("dealdeptcd"   ,dealdeptcd );      // \uad00\ub9ac\ubd80\uc11c\ucf54\ub4dc
		session.setAttribute("dealdeptnm"   ,dealdeptnm );      // \uad00\ub9ac\ubd80\uc11c\uba85
		session.setAttribute("areacd"       ,areacd     );      // \uad00\ub9ac\uc9c0\uc5ed\ucf54\ub4dc
		session.setAttribute("areanm"       ,areanm     );      // \uad00\ub9ac\uc9c0\uc5ed\uba85
		session.setAttribute("deptplacyn"   ,deptplacyn );      // \ubd80\uc11c\uc7a5\uc5ec\ubd80
		session.setAttribute("jobcd"        ,jobcd      );      // \uc5c5\ubb34\uad6c\ubd84
		session.setAttribute("jobnm"        ,jobnm      );      // \uc5c5\ubb34\uad6c\ubd84\uba85
		session.setAttribute("posicd"       ,posicd     );      // \uc9c1\ucc45\ucf54\ub4dc
		session.setAttribute("posinm"       ,posinm     );      // \uc9c1\ucc45\uba85
		session.setAttribute("usertypecd"   ,usertypecd );      // \uc0ac\uc6d0\uad6c\ubd84\ucf54\ub4dc
		session.setAttribute("usertypenm"   ,usertypenm );      // \uc0ac\uc6d0\uad6c\ubd84\uba85
		session.setAttribute("email"        ,email      );      // \uc774\uba54\uc77c
		
		// CIIS \ucd94\uac00 \ud56d\ubaa9\ub4e4  - \ubcf8\ubd80(\uba85),\ud30c\ud2b8(\uba85) LDAP\uc5d0\uc11c \uad00\ub9ac \uc548\ub418\ub294 \uad00\uacc4\ub85c \uc0ad\uc81c\ud568.
		//session.setAttribute("hdqtcd"     ,hdqtcd     );      // \ubcf8\ubd80        
		//session.setAttribute("hdqtnm"     ,hdqtnm     );      // \ubcf8\ubd80\uba85      
		//session.setAttribute("partcd"     ,partcd     );      // \ud30c\ud2b8\ucf54\ub4dc    
		//session.setAttribute("partnm"     ,partnm     );      // \ud30c\ud2b8\uba85      
		session.setAttribute("hdqtplacyn" 	,hdqtplacyn );      // \ubcf8\ubd80\uc7a5\uc5ec\ubd80  
		session.setAttribute("partplacyn" 	,partplacyn );      // \ud30c\ud2b8\uc7a5\uc5ec\ubd80  
		session.setAttribute("dealmedicd"  	,dealmedicd );      // \uad00\ub9ac\ub9e4\uccb4\ucf54\ub4dc
		session.setAttribute("mobile"  	,mobile );      // \uad00\ub9ac\ub9e4\uccb4\ucf54\ub4dc		
		
//System.out.println("request.getHeader(emp_nm) : " + request.getHeader("EMP_NM"));


//System.out.println("  emp_nm  : " + emp_nm);
//System.out.println("  sess emp_nm : " + Util.getSessionParameterValue(request, "emp_nm", true));
  

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
		// LDAP \ub85c\uadf8\uc778 \uc5c5\ub370\uc774\ud2b8
        // ldapp.UpdateInfoLogin updateInfoLogin = new ldapp.UpdateInfoLogin();
        // updateInfoLogin.updateldap(uid);


      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	String domainName = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+request.getContextPath();
	String strMenuUrl = "";
	String strmainFrame = "";

System.out.println("uid : " + uid);
	if (uid == null) {
		uid = GetCookie(request,response,"uid");
System.out.println("uid null : " + uid);
	}

	if (uid == null){
		response.sendRedirect("/common/jsp/logclose.jsp"); 
	} else {
		strMenuUrl = "/co/mng/1000";
		strmainFrame = "/common/xrw/mainFrame.xrw";
	}

	System.out.println("strmainFrame == " + strmainFrame);
	System.out.println("domainName == " + domainName);

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print(( uid ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print(( emp_no ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print(( emp_nm ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print(( cmpycd ));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print(( deptcd ));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print(( deptnm ));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print(( selldeptcd ));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print(( selldeptnm ));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( areacd ));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( areanm ));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      out.print(( deptplacyn ));
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print(( jobcd ));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print(( jobnm ));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print(( posicd ));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print(( posinm ));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print(( usertypecd ));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print(( usertypenm ));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( email ));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      out.print(( dealdeptcd ));
      out.write(_jsp_string21, 0, _jsp_string21.length);
      out.print(( dealdeptnm ));
      out.write(_jsp_string22, 0, _jsp_string22.length);
      out.print(( hdqtcd ));
      out.write(_jsp_string23, 0, _jsp_string23.length);
      out.print(( hdqtnm ));
      out.write(_jsp_string24, 0, _jsp_string24.length);
      out.print(( partcd ));
      out.write(_jsp_string25, 0, _jsp_string25.length);
      out.print(( partnm ));
      out.write(_jsp_string26, 0, _jsp_string26.length);
      out.print(( hdqtplacyn ));
      out.write(_jsp_string27, 0, _jsp_string27.length);
      out.print(( partplacyn ));
      out.write(_jsp_string28, 0, _jsp_string28.length);
      out.print(( dealmedicd ));
      out.write(_jsp_string29, 0, _jsp_string29.length);
      out.print(( domainName ));
      out.write(_jsp_string30, 0, _jsp_string30.length);
      out.print(( mobile ));
      out.write(_jsp_string31, 0, _jsp_string31.length);
       if(cmpycd.equals("100")){
      out.write(_jsp_string32, 0, _jsp_string32.length);
      }else{
      out.write(_jsp_string33, 0, _jsp_string33.length);
      out.print((cmpynm));
      out.write(_jsp_string34, 0, _jsp_string34.length);
      }
      out.write(_jsp_string35, 0, _jsp_string35.length);
      out.print((deptnm));
      out.write(_jsp_string36, 0, _jsp_string36.length);
      out.print((emp_nm));
      out.write(_jsp_string37, 0, _jsp_string37.length);
      out.print(( domainName + strMenuUrl ));
      out.write(_jsp_string38, 0, _jsp_string38.length);
      out.print(( domainName + strMenuUrl ));
      out.write(_jsp_string39, 0, _jsp_string39.length);
      out.print(( strmainFrame ));
      out.write(_jsp_string40, 0, _jsp_string40.length);
      out.print(( domainName ));
      out.write(_jsp_string41, 0, _jsp_string41.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/jsp/main.jsp"), 1551426275045768615L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string40;
  private final static char []_jsp_string27;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string18;
  private final static char []_jsp_string10;
  private final static char []_jsp_string15;
  private final static char []_jsp_string32;
  private final static char []_jsp_string28;
  private final static char []_jsp_string26;
  private final static char []_jsp_string25;
  private final static char []_jsp_string41;
  private final static char []_jsp_string35;
  private final static char []_jsp_string24;
  private final static char []_jsp_string5;
  private final static char []_jsp_string38;
  private final static char []_jsp_string3;
  private final static char []_jsp_string23;
  private final static char []_jsp_string34;
  private final static char []_jsp_string22;
  private final static char []_jsp_string30;
  private final static char []_jsp_string39;
  private final static char []_jsp_string19;
  private final static char []_jsp_string36;
  private final static char []_jsp_string4;
  private final static char []_jsp_string20;
  private final static char []_jsp_string31;
  private final static char []_jsp_string29;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string37;
  private final static char []_jsp_string12;
  private final static char []_jsp_string8;
  private final static char []_jsp_string21;
  private final static char []_jsp_string0;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string6;
  private final static char []_jsp_string1;
  private final static char []_jsp_string33;
  static {
    _jsp_string40 = "\", \"100%\", \"100%\", \"".toCharArray();
    _jsp_string27 = "\">\r\n	<input type=\"hidden\" name=\"partplacyn\"	value=\"".toCharArray();
    _jsp_string11 = "\">\r\n	<input type=\"hidden\" name=\"areanm\"		value=\"".toCharArray();
    _jsp_string16 = "\">\r\n	<input type=\"hidden\" name=\"posinm\"		value=\"".toCharArray();
    _jsp_string18 = "\">\r\n	<input type=\"hidden\" name=\"usertypenm\"	value=\"".toCharArray();
    _jsp_string10 = "\">\r\n	<input type=\"hidden\" name=\"areacd\"		value=\"".toCharArray();
    _jsp_string15 = "\">\r\n	<input type=\"hidden\" name=\"posicd\"		value=\"".toCharArray();
    _jsp_string32 = "\r\n		                	<td align=\"left\">\r\n		                		&nbsp;<script type=\"text/javascript\">swfShow(\"/flash/logo02.swf\", 100, 22)</script><br>\r\n		                	</td>\r\n			                ".toCharArray();
    _jsp_string28 = "\">\r\n	<input type=\"hidden\" name=\"dealmedicd\"	value=\"".toCharArray();
    _jsp_string26 = "\">\r\n	<input type=\"hidden\" name=\"hdqtplacyn\"	value=\"".toCharArray();
    _jsp_string25 = "\">\r\n	<input type=\"hidden\" name=\"partnm\"		value=\"".toCharArray();
    _jsp_string41 = "\");\r\n							</script>\r\n						</div>\r\n						\r\n<!-- fileDownload\ub97c \uc704\ud55c hidden iframe \uc2dc\uc791 -->\r\n	<div><iframe id=\"hiddenIframe\" src=\"\" style=\"width: 0px; height: 0px; visibility: hidden;\" ></iframe></div>\r\n<!-- fileDownload\ub97c \uc704\ud55c hidden iframe \ub05d -->						\r\n					</td>\r\n				</tr> \r\n			</table>\r\n\r\n		</td>\r\n	</tr>\r\n</table>\r\n\r\n</body>\r\n</HTML>\r\n".toCharArray();
    _jsp_string35 = "\r\n			                <!-- img src=\"/images/Logo_Txt.gif\" width=\"100\" height=\"20\" alt=\"\" -->\r\n			              </tr>\r\n			              <tr>\r\n			                <td valign=\"bottom\" height=\"22\" align=\"center\"><font style=\"font-size:9pt; color:#808080;filter:glow(color=green, strength=8)\">".toCharArray();
    _jsp_string24 = "\">\r\n	<input type=\"hidden\" name=\"partcd\"		value=\"".toCharArray();
    _jsp_string5 = "\">\r\n	<input type=\"hidden\" name=\"cmpycd\"		value=\"".toCharArray();
    _jsp_string38 = "\", \"100%\", \"26\");\r\n                                //TFMenuWrite(TFMenuControlLocation, \"TFMenu\", \"".toCharArray();
    _jsp_string3 = "\">\r\n	<input type=\"hidden\" name=\"emp_no\"		value=\"".toCharArray();
    _jsp_string23 = "\">\r\n	<input type=\"hidden\" name=\"hdqtnm\"		value=\"".toCharArray();
    _jsp_string34 = "</b></font></span>\r\n			                </td>\r\n			                ".toCharArray();
    _jsp_string22 = "\">\r\n	<input type=\"hidden\" name=\"hdqtcd\"		value=\"".toCharArray();
    _jsp_string30 = "\">\r\n	<input type=\"hidden\" name=\"mobile\"	value=\"".toCharArray();
    _jsp_string39 = "\", \"998\", \"26\");\r\n                            </script>\r\n                        </div>\r\n                    </td>\r\n                    <td width=\"5\" background=\"transparent\"></td>\r\n                </tr>\r\n                <tr height=\"8\">\r\n                    <td width=\"20\" background=\"transparent\"></td>\r\n                    <td colspan=3 width=\"*\" align=\"right\" valign=\"bottom\"></td>\r\n                    <td width=\"5\" background=\"transparent\"></td>\r\n                </tr>\r\n            </table>\r\n            <!-- =============================================================================== -->\r\n        </td>\r\n    </tr>\r\n	<tr>\r\n		<td>\r\n\r\n			<!-- ===================== TF Framework \ubd80\ubd84 =======================================  -->\r\n			<table cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" height=\"100%\" border=\"0\">\r\n				<tr>\r\n					<td width=\"100%\" height=\"100%\" style=\"border:0px; padding:0px;\">\r\n						<div id=\"TFViewerControlLocation\">\r\n							<script>\r\n								TFViewerWrite(TFViewerControlLocation, \"mainFrame\", \"".toCharArray();
    _jsp_string19 = "\">\r\n	<input type=\"hidden\" name=\"email\"		value=\"".toCharArray();
    _jsp_string36 = "&nbsp;".toCharArray();
    _jsp_string4 = "\">\r\n	<input type=\"hidden\" name=\"emp_nm\"		value=\"".toCharArray();
    _jsp_string20 = "\">\r\n	<input type=\"hidden\" name=\"dealdeptcd\"	value=\"".toCharArray();
    _jsp_string31 = "\">\r\n	\r\n</form>\r\n\r\n<table cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" height=\"100%\" border=\"0\">\r\n    <tr height=\"70\">\r\n        <td>\r\n            <!-- ===================== TFMenu \ubd80\ubd84 ============================================= -->\r\n            <table cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" height=\"70\" border=\"0\" background=\"/images/top_bg.gif\">\r\n                <tr>\r\n					<td width=\"20\" background=\"transparent\"></td>                \r\n                    <!--td valign=\"middle\" rowspan=3 border=0 align=\"left\" width=\"236\" height=\"70\">\r\n                    	<img width=\"236\" height=\"60\" src=\"/images/top_logo3.gif\">\r\n                    </td-->\r\n			        <td valign=\"middle\" rowspan=3 border=0 align=\"left\" width=\"100\" height=\"70\">\r\n			        	<!--img src=\"/images/Logo.gif\" width=\"115\" height=\"46\" alt=\"\"-->\r\n			        	<!--img src=\"/images/Logo.gif\" width=\"100\" height=\"40\" alt=\"\"-->\r\n			        	<script type=\"text/javascript\">swfShow(\"/flash/logo01.swf\", 115, 46)</script><br>\r\n			        </td>\r\n			        <td valign=\"middle\" rowspan=3 width=\"126\" height=\"70\">\r\n			            <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n			              <tr>\r\n		                	".toCharArray();
    _jsp_string29 = "\">\r\n	<input type=\"hidden\" name=\"domainnm\"	value=\"".toCharArray();
    _jsp_string2 = "\r\n<HTML>\r\n<HEAD>\r\n<META http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n<title>\uc870\uc120\uc77c\ubcf4\ud1b5\ud569\uc815\ubcf4\uc9c0\uc6d0\uc2dc\uc2a4\ud15c</title>\r\n<Script language=\"javascript\" for=\"TFMenu\" event=\"OnClickedMenuItem(idx)\">\r\n	//\ud074\ub9ad\ud55c \uba54\ub274\uc758 \ud558\uc704\ub2e8\uacc4\ub97c \ub808\ud504\ud2b8\uba54\ub274\ud2b8\ub9ac\ub85c \ubcf4\ub0b4\uae30\r\n	document.all.mainFrame.window.javaScript.loadLeftMenuXml(idx);\r\n	document.all.mainFrame.window.javaScript.onBtnTree(\"top\");\r\n	//\uc5c5\ubb34\ud654\uba74\uc744 \ud638\ucd9c\r\n	//document.all.mainFrame.window.javaScript.onLoadPage(idx);\r\n</script>\r\n<script language=\"javascript\" src=\"/js/Layer.js\"></script>\r\n<script language=\"javascript\" src=\"/js/Mouse.js\"></script>\r\n<script language=\"javascript\" src=\"/js/Fire.js\"></script>\r\n<script language=\"javascript\" src=\"/js/TFControlWrite.js\"></script>\r\n<script language=\"javascript\" src=\"/js/swfShow.js\"></script>\r\n<script language=\"javascript\">\r\n    function jsNewModalWinNoS( url, args, sizeW, sizeH )\r\n    {\r\n        opt = \"center:yes; help:no; resizable:no; scroll:no; status:no; location=no;\";\r\n        sizeH = parseInt(sizeH) + 20;\r\n        window.showModalDialog(url, args, \"dialogWidth:\" + sizeW + \"px; dialogHeight:\" + sizeH  +\"px; \"+ opt );\r\n        return;\r\n    }\r\n	function pop_system(){\r\n		jsNewModalWinNoS(\"/html/popup01_2.html\",\"a\",\"450\",\"500\");\r\n	}\r\n\r\n	function JSFX_StartEffects(){\r\n				JSFX.Fire(40,0);\r\n	}\r\n</script>\r\n</HEAD>\r\n<BODY border=\"0\" leftmargin=\"0\" topmargin=\"0\" rightmargin=\"0\" bottommargin=\"0\" cellpadding=\"0\" cellspacing=\"0\" scroll=\"no\">\r\n\r\n<form name=\"SessionInfo\">\r\n	<input type=\"hidden\" name=\"uid\"			value=\"".toCharArray();
    _jsp_string14 = "\">\r\n	<input type=\"hidden\" name=\"jobnm\"		value=\"".toCharArray();
    _jsp_string37 = "</font></td>\r\n			              </tr>\r\n			          </table>\r\n			        </td>\r\n                    <td width=\"*\" valign=\"bottom\" background=\"transparent\">\r\n						<script type=\"text/javascript\">swfShow(\"/flash/ciis_txt.swf\", 483, 24)</script><br>                    \r\n                    	<!--font size=\"2\">\ud1b5\ud569\uc815\ubcf4\uc9c0\uc6d0\uc2dc\uc2a4\ud15c(CIIS : Chosunilbo Integrated Information System)</font-->\r\n                    </td>\r\n                    <td align=\"right\" valign=\"bottom\" background=\"transparent\" height=\"18\">\r\n                    		<!--http://eipt.chosun.com:7777/manual/index.jsp-->\r\n                        <a href=\"/common/jsp/main.jsp\"><img height=\"18\" border=0 src=\"/images/01.gif\"></a>\r\n                        <a href=\"_self\" onclick=\"pop_system();return false;\"><img height=\"18\" border=0 src=\"/images/03.gif\"></a>\r\n                        <a href=\"/common/jsp/logout.jsp\"><img height=\"18\" border=0 src=\"/images/04.gif\"></a>\r\n                    </td>\r\n                    <td width=\"5\"></td>\r\n                </tr>\r\n                <tr height=\"26\">\r\n                    <td width=\"20\" background=\"transparent\"></td>\r\n                    <td colspan=3 width=\"*\" align=\"left\" valign=\"bottom\">\r\n                        <div id=\"TFMenuControlLocation\">\r\n                            <script>\r\n                                 TFMenuWrite(TFMenuControlLocation, \"TFMenu\", \"".toCharArray();
    _jsp_string12 = "\">\r\n	<input type=\"hidden\" name=\"deptplacyn\"	value=\"".toCharArray();
    _jsp_string8 = "\">\r\n	<input type=\"hidden\" name=\"selldeptcd\"	value=\"".toCharArray();
    _jsp_string21 = "\">\r\n	<input type=\"hidden\" name=\"dealdeptnm\"	value=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string13 = "\">\r\n	<input type=\"hidden\" name=\"jobcd\"		value=\"".toCharArray();
    _jsp_string17 = "\">\r\n	<input type=\"hidden\" name=\"usertypecd\"	value=\"".toCharArray();
    _jsp_string7 = "\">\r\n	<input type=\"hidden\" name=\"deptnm\"		value=\"".toCharArray();
    _jsp_string9 = "\">\r\n	<input type=\"hidden\" name=\"selldeptnm\"	value=\"".toCharArray();
    _jsp_string6 = "\">\r\n	<input type=\"hidden\" name=\"deptcd\"		value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n".toCharArray();
    _jsp_string33 = "\r\n			                <td align=\"center\">\r\n			                	&nbsp;<span style=\"COLOR:#6b6b6b;FILTER:shadow(color=#cccccc);height:8px\"><font size=5><b>".toCharArray();
  }
}
