/*
 * JSP generated by Resin-3.1.9 (built Mon, 13 Apr 2009 11:09:12 PDT)
 */

package _jsp._common._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.io.*;
import java.sql.*;
import java.util.*;
import kr.co.comsquare.rwXmlLib.*;
import kr.co.comsquare.db.*;
import kr.co.comsquare.util.Tokenizer;
import chosun.ciis.co.mng.rec.*;
import chosun.ciis.co.mng.ds.*;;

public class _menu__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/xml; charset=EUC-KR");
    request.setCharacterEncoding("EUC-KR");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
  response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // http 1.1
  response.setHeader("Pragma","No-cache"); //HTTP 1.0 
	response.setDateHeader("Expires", 0); 

      out.write(_jsp_string1, 0, _jsp_string1.length);
      
	CO_MNG_1000_LDataSet ds = (CO_MNG_1000_LDataSet)request.getAttribute("ds");
	for(int i = 0; i < ds.curlist.size(); i++) {
		CO_MNG_1000_LCURLISTRecord rec = (CO_MNG_1000_LCURLISTRecord)ds.curlist.get(i);

      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((rec.menu_id));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((rec.menu_nm));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      		
	} 

      out.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 5783496155892875126L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("common/jsp/menu.jsp"), -4873285020684457763L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = "\r\n	<Main itemID=\"".toCharArray();
    _jsp_string1 = "\r\n<?xml version=\"1.0\" encoding=\"EUC-KR\"?>\r\n<Menu type=\"fulldown\" borderstyle=\"1\" \r\nfont-family=\"\ub3cb\uc6c0\" font-size=\"13\" font-color=\"#ffffff\" font-bold=\"true\" \r\nbgcolor=\"#839fc7\" mecolor=\"#05337E\">\r\n".toCharArray();
    _jsp_string5 = "\r\n</Menu>\r\n".toCharArray();
    _jsp_string4 = "\" select-bgcolor=\"#05337E\" bgcolor=\"#839fc7\"/>	\r\n".toCharArray();
    _jsp_string3 = "\" name=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
